export const sampleMembers = [
  {
    id: "MEM001",
    name: "Dawit Tesfaye",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM002",
    name: "Selam Tadesse",
    training: "Bodybuilding",
    status: "Inactive",
  },
  {
    id: "MEM003",
    name: "Nahom Alemu",
    training: "Zumba",
    status: "Active",
  },
  {
    id: "MEM004",
    name: "Mekdes Abebe",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM005",
    name: "Yohannes Girma",
    training: "CrossFit",
    status: "Inactive",
  },
  {
    id: "MEM006",
    name: "Hana Mohammed",
    training: "Pilates",
    status: "Active",
  },
  {
    id: "MEM007",
    name: "Tewodros Assefa",
    training: "Weight Training",
    status: "Active",
  },
  {
    id: "MEM008",
    name: "Alemnesh Bekele",
    training: "Zumba",
    status: "Inactive",
  },
  {
    id: "MEM009",
    name: "Kaleb Demissie",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM010",
    name: "Rahel Yohannes",
    training: "Bodybuilding",
    status: "Active",
  },
  {
    id: "MEM011",
    name: "Elias Tadesse",
    training: "Swimming",
    status: "Inactive",
  },
  {
    id: "MEM012",
    name: "Sara Hailu",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM013",
    name: "Biniam Getachew",
    training: "Martial Arts",
    status: "Active",
  },
  {
    id: "MEM014",
    name: "Frehiwot Alemayehu",
    training: "Pilates",
    status: "Inactive",
  },
  {
    id: "MEM015",
    name: "Samuel Mekonnen",
    training: "CrossFit",
    status: "Active",
  },
  {
    id: "MEM016",
    name: "Marta Kebede",
    training: "Zumba",
    status: "Active",
  },
  {
    id: "MEM017",
    name: "Daniel Fikadu",
    training: "Weight Training",
    status: "Inactive",
  },
  {
    id: "MEM018",
    name: "Tigist Worku",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM019",
    name: "Yared Haile",
    training: "Bodybuilding",
    status: "Active",
  },
  {
    id: "MEM020",
    name: "Birtukan Solomon",
    training: "Swimming",
    status: "Inactive",
  },
  // Continuing with 180 more members...
  {
    id: "MEM021",
    name: "Ashenafi Tekle",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM022",
    name: "Mulugeta Abate",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM023",
    name: "Zelalem Assefa",
    training: "CrossFit",
    status: "Inactive",
  },
  {
    id: "MEM024",
    name: "Hirut Dereje",
    training: "Zumba",
    status: "Active",
  },
  {
    id: "MEM025",
    name: "Abel Teshome",
    training: "Weight Training",
    status: "Active",
  },
  {
    id: "MEM026",
    name: "Meseret Belay",
    training: "Pilates",
    status: "Inactive",
  },
  {
    id: "MEM027",
    name: "Eyob Gebre",
    training: "Bodybuilding",
    status: "Active",
  },
  {
    id: "MEM028",
    name: "Mihret Ayele",
    training: "Swimming",
    status: "Active",
  },
  {
    id: "MEM029",
    name: "Temesgen Worku",
    training: "Martial Arts",
    status: "Inactive",
  },
  {
    id: "MEM030",
    name: "Adanech Girma",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM031",
    name: "Getnet Asrat",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM032",
    name: "Aster Mengistu",
    training: "CrossFit",
    status: "Inactive",
  },
  {
    id: "MEM033",
    name: "Bereket Solomon",
    training: "Zumba",
    status: "Active",
  },
  {
    id: "MEM034",
    name: "Elshadai Yohannes",
    training: "Weight Training",
    status: "Active",
  },
  {
    id: "MEM035",
    name: "Fasika Mekuria",
    training: "Pilates",
    status: "Inactive",
  },
  {
    id: "MEM036",
    name: "Girma Lemma",
    training: "Bodybuilding",
    status: "Active",
  },
  {
    id: "MEM037",
    name: "Haben Tesfaye",
    training: "Swimming",
    status: "Active",
  },
  {
    id: "MEM038",
    name: "Ibsaa Demissie",
    training: "Martial Arts",
    status: "Inactive",
  },
  {
    id: "MEM039",
    name: "Jemberu Hailu",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM040",
    name: "Kidan Assefa",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM041",
    name: "Liya Tadesse",
    training: "CrossFit",
    status: "Inactive",
  },
  {
    id: "MEM042",
    name: "Mekonnen Abebe",
    training: "Zumba",
    status: "Active",
  },
  {
    id: "MEM043",
    name: "Nardos Mekuria",
    training: "Weight Training",
    status: "Active",
  },
  {
    id: "MEM044",
    name: "Oumer Ali",
    training: "Pilates",
    status: "Inactive",
  },
  {
    id: "MEM045",
    name: "Petros Wolde",
    training: "Bodybuilding",
    status: "Active",
  },
  {
    id: "MEM046",
    name: "Qwara Bekele",
    training: "Swimming",
    status: "Active",
  },
  {
    id: "MEM047",
    name: "Rediet Ashenafi",
    training: "Martial Arts",
    status: "Inactive",
  },
  {
    id: "MEM048",
    name: "Selamawit Gebre",
    training: "Yoga",
    status: "Active",
  },
  {
    id: "MEM049",
    name: "Tariku Lemma",
    training: "Cardio",
    status: "Active",
  },
  {
    id: "MEM050",
    name: "Urge Belay",
    training: "CrossFit",
    status: "Inactive",
  },
  {
    id: "MEM200",
    name: "Zufan Asrat",
    training: "Pilates",
    status: "Active",
  },
];
