export const sampleMembers = [
  {
    fullName: "Dawit Tesfaye",
    phoneNumber: "0912345678",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-08-05",
  },
  {
    fullName: "Abeba Getachew",
    phoneNumber: "0911223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-12-10",
  },
  {
    fullName: "Yohannes Assefa",
    phoneNumber: "0922334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-09-15",
  },
  {
    fullName: "Selamawit Girma",
    phoneNumber: "0933445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-07-20",
  },
  {
    fullName: "Mekonnen Haile",
    phoneNumber: "0944556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-01-30",
  },
  {
    fullName: "Tigist Worku",
    phoneNumber: "0955667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-08-12",
  },
  {
    fullName: "Getachew Kebede",
    phoneNumber: "0966778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-10-05",
  },
  {
    fullName: "Alemnesh Bekele",
    phoneNumber: "0977889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-07-30",
  },
  {
    fullName: "Habtamu Tadesse",
    phoneNumber: "0988990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-03-15",
  },
  {
    fullName: "Birtukan Fikadu",
    phoneNumber: "0999001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-08-25",
  },
  {
    fullName: "Samuel Lemma",
    phoneNumber: "0910112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-11-10",
  },
  {
    fullName: "Eden Teshome",
    phoneNumber: "0921223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-09-05",
  },
  {
    fullName: "Daniel Asrat",
    phoneNumber: "0932334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-02-20",
  },
  {
    fullName: "Hana Solomon",
    phoneNumber: "0943445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-08-15",
  },
  {
    fullName: "Kaleb Girma",
    phoneNumber: "0954556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-10-30",
  },
  {
    fullName: "Marta Yohannes",
    phoneNumber: "0965667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-09-01",
  },
  {
    fullName: "Nahom Tekle",
    phoneNumber: "0976778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-04-10",
  },
  {
    fullName: "Sara Mekonnen",
    phoneNumber: "0987889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-08-20",
  },
  {
    fullName: "Temesgen Abebe",
    phoneNumber: "0998990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-11-25",
  },
  {
    fullName: "Zewditu Tadesse",
    phoneNumber: "0910001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-09-10",
  },
  {
    fullName: "Fitsum Demisse",
    phoneNumber: "0921112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-05-15",
  },
  {
    fullName: "Genet Assefa",
    phoneNumber: "0932223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-10-05",
  },
  {
    fullName: "Yared Mulatu",
    phoneNumber: "0943334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-12-20",
  },
  {
    fullName: "Rahel Asrat",
    phoneNumber: "0954445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-10-15",
  },
  {
    fullName: "Ashenafi Kebede",
    phoneNumber: "0965556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-06-30",
  },
  {
    fullName: "Mihret Abate",
    phoneNumber: "0976667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-11-01",
  },
  {
    fullName: "Eyob Getahun",
    phoneNumber: "0987778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-01-10",
  },
  {
    fullName: "Betelhem Yared",
    phoneNumber: "0998889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2025-11-20",
  },
  {
    fullName: "Desta Lemma",
    phoneNumber: "0919990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-07-15",
  },
  {
    fullName: "Kidan Hailu",
    phoneNumber: "0920001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-12-10",
  },
  {
    fullName: "Tewodros Girma",
    phoneNumber: "0931112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-02-05",
  },
  {
    fullName: "Elsa Mekuria",
    phoneNumber: "0942223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2025-12-30",
  },
  {
    fullName: "Girma Tesfaye",
    phoneNumber: "0953334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-08-20",
  },
  {
    fullName: "Hirut Assefa",
    phoneNumber: "0964445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-01-15",
  },
  {
    fullName: "Solomon Demeke",
    phoneNumber: "0975556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-03-30",
  },
  {
    fullName: "Meseret Abebe",
    phoneNumber: "0986667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-02-01",
  },
  {
    fullName: "Abel Tadesse",
    phoneNumber: "0997778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-01-10",
  },
  {
    fullName: "Mulugeta Worku",
    phoneNumber: "0918889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-03-20",
  },
  {
    fullName: "Frehiwot Lemma",
    phoneNumber: "0929990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-05-25",
  },
  {
    fullName: "Bereket Assefa",
    phoneNumber: "0930001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-04-10",
  },
  {
    fullName: "Tsehay Kebede",
    phoneNumber: "0941112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-02-15",
  },
  {
    fullName: "Yonas Girma",
    phoneNumber: "0952223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-05-05",
  },
  {
    fullName: "Aster Yohannes",
    phoneNumber: "0963334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-07-20",
  },
  {
    fullName: "Tilahun Asrat",
    phoneNumber: "0974445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-06-15",
  },
  {
    fullName: "Selamawit Abate",
    phoneNumber: "0985556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-08-30",
  },
  {
    fullName: "Mekdes Hailu",
    phoneNumber: "0996667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-08-01",
  },
  {
    fullName: "Binyam Lemma",
    phoneNumber: "0917778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-10-10",
  },
  {
    fullName: "Eyerusalem Tekle",
    phoneNumber: "0928889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-09-20",
  },
  {
    fullName: "Henok Tadesse",
    phoneNumber: "0939990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-10-15",
  },
  {
    fullName: "Mahlet Assefa",
    phoneNumber: "0940001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-11-10",
  },
  {
    fullName: "Ruth Abraham",
    phoneNumber: "0951112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-12-05",
  },
  {
    fullName: "Samuel Getnet",
    phoneNumber: "0962223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-11-10",
  },
  {
    fullName: "Martha Yoseph",
    phoneNumber: "0973334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-11-15",
  },
  {
    fullName: "Nathaniel Solomon",
    phoneNumber: "0984445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2026-10-20",
  },
  {
    fullName: "Esther Daniel",
    phoneNumber: "0995556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-09-30",
  },
  {
    fullName: "Ephrem Asmelash",
    phoneNumber: "0916667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2026-12-12",
  },
  {
    fullName: "Judith Teshome",
    phoneNumber: "0927778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-01-05",
  },
  {
    fullName: "Simon Petros",
    phoneNumber: "0938889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-01-30",
  },
  {
    fullName: "Lydia Michael",
    phoneNumber: "0949990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-03-15",
  },
  {
    fullName: "Philipos Girma",
    phoneNumber: "0950001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-02-25",
  },
  {
    fullName: "Rebekah Asrat",
    phoneNumber: "0961112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-04-10",
  },
  {
    fullName: "Thomas Mekonnen",
    phoneNumber: "0972223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-03-05",
  },
  {
    fullName: "Deborah Samuel",
    phoneNumber: "0983334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2028-02-20",
  },
  {
    fullName: "Josephine Kebede",
    phoneNumber: "0994445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-05-15",
  },
  {
    fullName: "Gideon Tesfaye",
    phoneNumber: "0915556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-07-30",
  },
  {
    fullName: "Rebecca Hailu",
    phoneNumber: "0926667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-06-01",
  },
  {
    fullName: "Benjamin Assefa",
    phoneNumber: "0937778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-04-10",
  },
  {
    fullName: "Sarah Yohannes",
    phoneNumber: "0948889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-08-20",
  },
  {
    fullName: "Daniel Getachew",
    phoneNumber: "0959990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-10-25",
  },
  {
    fullName: "Ruth Mekuria",
    phoneNumber: "0960001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-09-10",
  },
  {
    fullName: "Solomon Tadesse",
    phoneNumber: "0971112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-05-15",
  },
  {
    fullName: "Hannah Girma",
    phoneNumber: "0982223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2027-11-05",
  },
  {
    fullName: "Paulos Asrat",
    phoneNumber: "0993334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-01-20",
  },
  {
    fullName: "Martha Lemma",
    phoneNumber: "0914445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2027-12-15",
  },
  {
    fullName: "Timothy Kebede",
    phoneNumber: "0925556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2028-06-30",
  },
  {
    fullName: "Grace Assefa",
    phoneNumber: "0936667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-02-01",
  },
  {
    fullName: "Stephen Hailu",
    phoneNumber: "0947778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-04-10",
  },
  {
    fullName: "Elizabeth Tekle",
    phoneNumber: "0958889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2028-03-20",
  },
  {
    fullName: "David Yared",
    phoneNumber: "0969990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-01-15",
  },
  {
    fullName: "Mary Samuel",
    phoneNumber: "0970001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-05-10",
  },
  {
    fullName: "Johnathan Assefa",
    phoneNumber: "0981112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2028-07-05",
  },
  {
    fullName: "Anna Girma",
    phoneNumber: "0992223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-06-30",
  },
  {
    fullName: "Markos Kebede",
    phoneNumber: "0913334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-02-20",
  },
  {
    fullName: "Rebecca Lemma",
    phoneNumber: "0924445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2028-08-15",
  },
  {
    fullName: "Gabriel Tadesse",
    phoneNumber: "0935556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-10-30",
  },
  {
    fullName: "Sarah Assefa",
    phoneNumber: "0946667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-09-01",
  },
  {
    fullName: "Nathan Hailu",
    phoneNumber: "0957778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2029-01-10",
  },
  {
    fullName: "Esther Yohannes",
    phoneNumber: "0968889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2028-11-20",
  },
  {
    fullName: "Peter Tekle",
    phoneNumber: "0979990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-03-25",
  },
  {
    fullName: "Ruth Asrat",
    phoneNumber: "0980001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2029-02-10",
  },
  {
    fullName: "Samuel Girma",
    phoneNumber: "0991112233",
    trainingType: "Crossfit",
    trainingSchedule: "Mon-Wed-Fri",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2030-01-15",
  },
  {
    fullName: "Deborah Kebede",
    phoneNumber: "0912223344",
    trainingType: "Cardio",
    trainingSchedule: "Daily PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-04-05",
  },
  {
    fullName: "Michael Assefa",
    phoneNumber: "0923334455",
    trainingType: "Weightlifting",
    trainingSchedule: "Tue-Thu-Sat",
    membershipPackage: "Quarterly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2029-06-20",
  },
  {
    fullName: "Lydia Lemma",
    phoneNumber: "0934445566",
    trainingType: "Yoga",
    trainingSchedule: "Mon-Wed-Fri AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-05-15",
  },
  {
    fullName: "Daniel Tadesse",
    phoneNumber: "0945556677",
    trainingType: "Boxing",
    trainingSchedule: "Daily AM",
    membershipPackage: "Yearly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2030-07-30",
  },
  {
    fullName: "Martha Hailu",
    phoneNumber: "0956667788",
    trainingType: "Pilates",
    trainingSchedule: "Tue-Thu-Sun",
    membershipPackage: "Monthly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2029-08-01",
  },
  {
    fullName: "Thomas Yohannes",
    phoneNumber: "0967778899",
    trainingType: "Swimming",
    trainingSchedule: "Weekends",
    membershipPackage: "Quarterly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-10-10",
  },
  {
    fullName: "Sarah Tekle",
    phoneNumber: "0978889900",
    trainingType: "Zumba",
    trainingSchedule: "Mon-Wed-Fri PM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-09-20",
  },
  {
    fullName: "Joseph Asrat",
    phoneNumber: "0989990011",
    trainingType: "HIIT",
    trainingSchedule: "Daily PM",
    membershipPackage: "Yearly",
    paymentStatus: "Unpaid",
    membershipExpiryDate: "2030-08-15",
  },
  {
    fullName: "Rebecca Girma",
    phoneNumber: "0990001122",
    trainingType: "Aerobics",
    trainingSchedule: "Tue-Thu-Sat AM",
    membershipPackage: "Monthly",
    paymentStatus: "Paid",
    membershipExpiryDate: "2029-11-10",
  },
];
